-- MySQL Script generated by MySQL Workbench
-- Sun Dec  3 23:53:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `razon_social` VARCHAR(45) NOT NULL,
  `cuit` INT NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicios` (
  `id_servicio` INT NOT NULL AUTO_INCREMENT,
  `nombre_servicio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_servicio`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`clientes_tiene_servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes_tiene_servicios` (
  `id_servicio_cliente` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_servicio` INT NOT NULL,
  PRIMARY KEY (`id_servicio_cliente`),
  INDEX `id_cliente2` (`id_cliente` ASC) VISIBLE,
  INDEX `id_servicio2` (`id_servicio` ASC) INVISIBLE,
  CONSTRAINT `id_cliente2`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`clientes` (`id_cliente`),
  CONSTRAINT `id_servicio2`
    FOREIGN KEY (`id_servicio`)
    REFERENCES `mydb`.`servicios` (`id_servicio`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`especialidades` (
  `id_especialidad` INT NOT NULL AUTO_INCREMENT,
  `nombre_especialidad` VARCHAR(45) NOT NULL,
  `tiempo_resolucion` INT NOT NULL,
  PRIMARY KEY (`id_especialidad`),
  UNIQUE INDEX `id_especialidad_UNIQUE` (`id_especialidad` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`tecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tecnicos` (
  `id_tecnico` INT NOT NULL AUTO_INCREMENT,
  `nombre_tecnico` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tecnico`),
  UNIQUE INDEX `id_tecnico_UNIQUE` (`id_tecnico` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`incidentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`incidentes` (
  `id_incidente` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `descripcion_problema` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `id_tecnico` INT NOT NULL,
  `fecha_inicio` DATETIME NULL DEFAULT NULL,
  `fecha_fin` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_incidente`),
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `id_tecnico_idx` (`id_tecnico` ASC) VISIBLE,
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`clientes` (`id_cliente`),
  CONSTRAINT `fk_tecnico`
    FOREIGN KEY (`id_tecnico`)
    REFERENCES `mydb`.`tecnicos` (`id_tecnico`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`tecnicos_tiene_especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tecnicos_tiene_especialidades` (
  `id_tecnico_especialidad` INT NOT NULL AUTO_INCREMENT,
  `id_tecnico` INT NOT NULL,
  `id_especialidad` INT NOT NULL,
  PRIMARY KEY (`id_tecnico_especialidad`),
  INDEX `tecnico_fk_idx` (`id_especialidad` ASC) VISIBLE,
  INDEX `especialidad_fk_idx` (`id_tecnico` ASC) VISIBLE,
  CONSTRAINT `especialidad_fk`
    FOREIGN KEY (`id_tecnico`)
    REFERENCES `mydb`.`tecnicos` (`id_tecnico`),
  CONSTRAINT `tecnico_fk`
    FOREIGN KEY (`id_especialidad`)
    REFERENCES `mydb`.`especialidades` (`id_especialidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
